"""Fourth revision

Revision ID: 6d9de603778f
Revises: ea323f4968c9
Create Date: 2023-07-13 19:40:20.876448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d9de603778f'
down_revision = 'ea323f4968c9'
branch_labels = None
depends_on = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade() -> None:
    """op.alter_column("business", "case_dropeed_letter", new_column_name="case_dropped_letter", existing_type=sa.Text, nullable=False)
    op.add_column(table_name='vehicles', column=sa.Column('type', sa.Enum("car", "pickup"), nullable=False))"""
    # ### end Alembic commands ###
